title: Petr Baldaev # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
I am a Data Scientist with experience working with large datasets,
utilizing machine learning methods, and capable of data visualization. I
also possess knowledge in statistics and mathematics, am skilled in
working with diverse data sources and teams, and am familiar with the
product development process.
  <br><br>
  Second description 
  <br><br>
  <a href="https://github.com/spqr-86">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
